[general]
live_config_reload = true
import = [
    "themes/catppuccin-mocha.toml"
]

[font]
size = 15

[font.normal]
family = "Sarasa Mono J"

[window]
option_as_alt = 'Both'
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 6
y = 4
