[general]
live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "Iosevka"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1

[window.padding]
x = 6
y = 4

# Carbonfox

# Default colors
[colors.primary]
background = '#161616'
foreground = '#f2f4f8'

[colors.selection]
text = 'CellForeground'
background = '#333333'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'
