-- Harpoon
-- m for mark, gfdsa on left hand
vim.keymap.set('n', '<M-m>', require('harpoon.mark').add_file)
vim.keymap.set('n', '<M-g>', require('harpoon.ui').toggle_quick_menu)
vim.keymap.set('n', '<M-f>', function()
  require('harpoon.ui').nav_file(1)
end)
vim.keymap.set('n', '<M-d>', function()
  require('harpoon.ui').nav_file(2)
end)
vim.keymap.set('n', '<M-s>', function()
  require('harpoon.ui').nav_file(3)
end)
vim.keymap.set('n', '<M-a>', function()
  require('harpoon.ui').nav_file(4)
end)
